name: 'Action Minecraft Bedrock Diagnose'
description: 'Tests the content of your minecraft project for errors and outputs them to the action console as well as mark it as failed'
author: Blockception Ltd
branding:
  icon: activity
  color: green
inputs:
  folder:
    description: The folder path to start at
    required: false    
    default: "${{ github.workspace }}"
runs:
  using: 'node12'
  main: 'dist/index.js'
