name: 'Action Minecraft Bedrock Diagnose'
description: 'Tests the content of your minecraft project for errors and outputs them to the action console as well as mark it as failed'
author: Blockception Ltd
branding:
  icon: activity
  color: green
inputs:
  folders:
    description: The folder path(s) to start at
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
